# Generated by Django 4.0.3 on 2022-04-08 15:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='session_id',
            field=models.UUIDField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
