# Generated by Django 4.0.3 on 2022-04-08 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_session_id_alter_event_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='key',
        ),
    ]
